spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 5
          max-interval: 5s
          multiplier: 2


server:
  port: 8081
  servlet:
    context-path: /movie-schedule-rest-api
logging:
  file:
    name: D:/Development/WS/log/local/movie-schedule-rest-api/movie-schedule-rest-api.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.example.movie.schedule: INFO
    org.springframework.web: TRACE
message:
  messageConfiguration:
    host: localhost
    port: 20004
    username: guest
    password: guest
    virtualHost: snk-rmq
  movieInventoryExchangeConfiguration:
    exchange: movieScheduleExchange
    routingKey: movie.inventory
  movieScheduleExchangeConfiguration:
    exchange: movieScheduleExchange
    routingKey: movie.schedule
